import type { Metadata } from "next";
import { fontSans } from "../lib/fonts";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex items-start justify-between ${fontSans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <main className="flex flex-col items-start h-screen w-full">
            <Header />
            <div className="w-full h-[calc(100vh - 70px)]">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
